#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'Sphinx==1.0b2','console_scripts','sphinx-build'
__requires__ = 'Sphinx==1.0b2'
import sys
from pkg_resources import load_entry_point

sys.exit(
   load_entry_point('Sphinx==1.0b2', 'console_scripts', 'sphinx-build')()
)
